title: Into The East
author: TheStormAfterTheCalm
email: thestormafterthecalm@gmail.com
description: We will share many subjects here
theme: minima
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
